name: p2p_call_sample
description: P2P Calls Sample

version: 1.5.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectycube_flutter_call_kit: ^2.2.1
  connectycube_sdk: ^2.2.3
  device_info_plus: ^3.2.3
  flutter:
    sdk: flutter
  flutter_background: ^1.1.0
  package_info_plus: ^1.4.2
  permission_handler: ^10.2.0
  platform_device_id: ^1.0.1
  shared_preferences: ^2.0.15
  universal_io: ^2.0.4
  web_browser_detect: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
